### ISSUE TITLE
Resource: fivetran_connector, config: environment

### ISSUE THREAD

**Issue by JLYambao** [fivetran/terraform-provider-fivetran#100]
The fivetran API for [Zuora Sandbox](https://fivetran.com/docs/rest-api/connectors/config#zuorasandbox) has a field "environment" which is not yet supported by terraform. Please add this as every time we run terraform, we still need to manually change the settings in fivetran.

```
{
    "service": "zuora_sandbox",
    "group_id": "target_group_id",
    "config": {
        "schema": "test_zuora",
        "client_id": "zuora_client_id",
        "client_secret": "zuora_client_secret",
        "is_multi_entity_feature_enabled": true,
        "entity_id": "zuora_entity_id",
        "environment": "zuora_sandbox_environment"
    }
}
```
![zoura_sandbox_config parameters](https://user-images.githubusercontent.com/127407485/224026004-9676c49d-c15d-4371-ad21-d1dd146623de.png)

**Comment by beevital** [comment]
Created an internal ticket for that.

**Comment by LukaDevic** [comment]
Hi @JLYambao , mentioned field wes added in latest fivetran terraform provider version: 0.6.17.
Please upgrade the provider version to it and u will be able to use the field.
Im closing this ticket.

![image](https://user-images.githubusercontent.com/43738975/231981449-1fb8d90e-7500-4f89-aa05-1eb32e5692a1.png)
