### ISSUE TITLE
Missing GA4 'properties' config

### ISSUE THREAD

**Issue by MikeyJL** [fivetran/terraform-provider-fivetran#106]
## Expected Behavior

I'm trying to create a GA4 to Snowflake connection but only selecting the appropriate GA4 accounts and properties

## Current Behavior

Following the [documentation here](https://fivetran.com/docs/rest-api/connectors/config#configparameters_88), I'm trying to specify the ```properties``` config parameter but it doesn't allow it so the connection is incomplete on Fivetran.

![Screenshot 2023-03-21 at 20 04 10](https://user-images.githubusercontent.com/63963445/226727891-e5364d42-cf7c-45e4-9075-efc4c65b4ea4.png)

```terraform
resource "fivetran_connector" "google_analytics_4" {
  group_id          = fivetran_destination.snowflake.group_id
  service           = "google_analytics_4"
  sync_frequency    = 1440
  paused            = false
  pause_after_trial = false
  run_setup_tests   = true

  destination_schema {
    name  = local.snowflake_schema
    table = "traffic_session_medium"
  }

  config {
    timeframe_months = "THREE"
    sync_mode        = "SPECIFIC_ACCOUNTS"
    accounts         = ["XXXXXXXXX"]
    properties       = ["XXXXXXXXX"] // throws an error on 'terraform apply' as it doesn't exist
    prebuilt_report  = "TRAFFIC_ACQUISITION_SESSION_MEDIUM_REPORT"
    client_id        = var.gcp_client_id
    client_secret    = var.gcp_client_secret
  }
}
```

## Steps to Reproduce

1. Mimic the above connector terraform config
2. See that if you don't specify ```properties```, after ```terraform apply``` succeeds, then the connection is incomplete.
3. Try now and add ```properties``` into the ```config``` block, and now see that ```terraform apply``` throws error ``` Error: Unsupported argument ... An argument named "properties" is not expected here.```

**Comment by beevital** [comment]
Created internal ticket for that. Will support the field in nearest releases.

**Comment by LukaDevic** [comment]
Hi @MikeyJL , mentioned field was added in latest fivetran terraform provider version 0.6.17.
Please upgrade the provider version to it and u will be able to use the field.
Im closing this ticket.

![image](https://user-images.githubusercontent.com/43738975/231981942-5da88ec3-1b6c-422c-9b53-defa05c632e2.png)
