### ISSUE TITLE
Can't complete the whole setup of a GCP cloudsql connector, without manual intervention in Fivetran UI 

### ISSUE THREAD

**Issue by anderskotsalaineneqt** [fivetran/terraform-provider-fivetran#107]
Fivetran provider version 0.6.11

I'm trying to use Terraform to create a GCP cloudsql postgres connector that uses an SSH tunnel to reach the source database. I can create the connector, but when I look in the Fivetran UI the connector is not running. If I then test the connection it brings up a popup where Fivetran goes through the different steps in establishing a connection. Once it reaches the step of connecting to the SSH tunnel host one gets a warning where one is asked if one trusts the SSH-key for the SSH-tunnel host. One has to accept this SSH-key and then then setup process resumes and then can proceed past the step where the connection to the SSH-tunnel host is established. The next step that stops the process is where the certificate from the google postegres DB has a CA that Fivetran does not trust, and so I as a user have to agree to trusting this certificate. Then the connection process restarts and can complete successfully.

This whole connection process is one I recognise from when I have set up the same type of connector directly in the FIvetran UI so I understand why it's happening. The prompts where Fivetran asks if I trust the SSH-host server and DB certificate are just part of the normal setup process.

My issue is that when I set up the connector via Terraform, and use the setting `run_setup_tests = "true"` then I would want this to result in the connector running successfully without any manual intervention. So I'm looking for some type of setting where one can specify that I trust all server SSH keys and certificates that pop up in the connection set up process.

/Anders

**Comment by beevital** [comment]
To setup SSH tunnel you should also approve SSH fingerprint manually or enable auto-trust mode using:
```
trust_fingerprints = "true"
```
https://registry.terraform.io/providers/fivetran/fivetran/latest/docs/resources/connector#trust_fingerprints

Please report here if it won't help to solve your issue.

**Comment by anderskotsalaineneqt** [comment]
Hi, thanks for the input. I had missed this optional setting. Thanks!
