### ISSUE TITLE
Trying to set connection_method for SFTP connector causes Terraform failure

### ISSUE THREAD

**Issue by anderskotsalaineneqt** [fivetran/terraform-provider-fivetran#109]
Hi,
I'm trying to create a SFTP-connector using Terraform. I have the following TF-config:

```
resource "fivetran_connector" "sftp_connector" {
  group_id          = data.fivetran_destination.destination.group_id
  service           = "sftp"
  sync_frequency    = var.sync_frequency_min
  run_setup_tests   = "true"
  paused            = var.paused
  pause_after_trial = false

  destination_schema {
    name  = var.destination_schema
    table = var.destination_table
  }

  config {
    connection_method   = var.connection_method
    is_keypair         = var.is_keypair
    password           = var.password
    user               = var.user
    host               = var.host
    port               = var.port
    prefix             = var.folder_path_to_sync
    pattern            = var.pattern
    file_type          = var.file_type
    on_error           = var.on_error
    append_file_option = var.append_file_option
    archive_pattern    = var.archive_pattern
    null_sequence      = var.null_sequence
    delimiter          = var.delimeter
    escape_char        = var.escape_char
    skip_before        = var.skip_before
    skip_after         = var.skip_after
  }
}
```
Running "terraform plan" I get the error below stating the a connection_method is not expected where I have placed it in my config. I have also tried placing the connection_method key inside destination_schema object but that did not work either.

<img width="977" alt="image" src="https://user-images.githubusercontent.com/111284232/229129308-360f9a1d-a34e-4bfd-be54-8e832c7a520c.png">

If I simply remove the connection_method from the config object then everything works, but then I guess Fivetran just is defaulting to the "direct" connection method. It seems like I can't use the expected parameter "connection_method" to control the connection method. According to the docs I think I'm doing things correctly but not getting it to work.

<img width="900" alt="image" src="https://user-images.githubusercontent.com/111284232/229070192-714f2063-b072-4718-ad53-85c7e2c6efbe.png">

**Comment by LukaDevic** [comment]
Hi @anderskotsalaineneqt, can you update Fivetran terraform provider to latest version, "connection_method" was added in 0.6.14 version release.

**Comment by anderskotsalaineneqt** [comment]
Yep this solve the issue. Only thing worth mentioning is that version 0.6.14 does not exist any more so I had to chose 0.6.15
