### ISSUE TITLE
json: cannot unmarshal number into Go struct field ConnectorConfigResponse.apps of type string

### ISSUE THREAD

**Issue by MikeyJL** [fivetran/terraform-provider-fivetran#110]
## Expected Behavior

Using the ```fivetran_connector``` resource to create new connectors.

## Current Behavior

It was working yesterday (30th March 23) when I created a new connector, but for some reason today all the ```fivetran_connector``` resource is now throwing the same error saying the below about ```ConnectorConfigResponse.apps``` even though I've not changed anything and it was working previously.

**Error**

```
json: cannot unmarshal number into Go struct field
ConnectorConfigResponse.apps of type string; code: Success; message:
```

**One of my previously working connector**

```terraform
resource "fivetran_connector" "ga4_projects" {
  group_id          = fivetran_destination.ga4_projects.group_id
  service           = "google_analytics_4"
  sync_frequency    = "1440"
  paused            = false
  pause_after_trial = false
  run_setup_tests   = true

  destination_schema {
    name = local.snowflake_raw_schema
  }

  config {
    timeframe_months = "ALL_TIME"
    sync_mode        = "ALL_ACCOUNTS"
    client_id        = "*********"
    client_secret    = "*********"

    reports {
      table           = "user_acquisition_first_user_source"
      config_type     = "PREBUILT"
      prebuilt_report = "USER_ACQUISITION_FIRST_USER_SOURCE_REPORT"
    }
    reports {
      table           = "events"
      config_type     = "PREBUILT"
      prebuilt_report = "EVENTS_REPORT"
    }
    reports {
      table           = "pages_title_and_screen_name"
      config_type     = "PREBUILT"
      prebuilt_report = "PAGES_TITLE_AND_SCREEN_NAME_REPORT"
    }
  }
}
```

## Steps to Reproduce

Not sure how you would but I guess you could start with upping a new connector?

**Comment by beevital** [comment]
could you please clarify - did you updated provider version or it just happened without any changes on your side?

**Comment by beevital** [comment]
Tested your config on latest provider version v0.6.16 - all works fine.
Successfully created/updated and deleted ga4 connector with your config.

**Comment by MikeyJL** [comment]
Hi @beevital thanks for looking into it, it's all good now. Think it was some bad states on my end so can close this issue.
