### ISSUE TITLE
Support for S3 destination

### ISSUE THREAD

**Issue by dominicroessner** [fivetran/terraform-provider-fivetran#111]
Any plans to support S3 as a service type in the [fivetran_destination](https://registry.terraform.io/providers/fivetran/fivetran/latest/docs/resources/destination#service) resource?

As of today it does not look like the REST API supports this yet.
https://fivetran.com/docs/rest-api/destinations/config

**Comment by beevital** [comment]
Created an internal ticket for that.

**Comment by LukaDevic** [comment]
S3 is supported in latest provider release - v0.7.0

@dominicroessner please download v0.7.0 to use S3 as a destination.

Closing this issue.

**Comment by dominicroessner** [comment]
Thank you @LukaDevic

**Comment by LukaDevic** [comment]
Hi @dominicroessner version v0.7.0 proved to be flawed, please dont use it. Latest v0.7.1 can be used, but that version still doesn't have support for requested s3 fields. 

We are working on version which will contain s3 fields and i will inform you when we release version which contains them.

**Comment by beevital** [comment]
@dominicroessner we have released v0.7.2-pre version and it includes support for missing fields.
