### ISSUE TITLE
Update method for SQL server connector don't seem to be accurate

### ISSUE THREAD

**Issue by anderskotsalaineneqt** [fivetran/terraform-provider-fivetran#116]
Hi,

We have an existing sql server connector that I imported out terraform state. The connector has the following update method:
<img width="693" alt="image" src="https://user-images.githubusercontent.com/111284232/232987434-2ee413dd-e8c2-458e-87e2-6cc5076c8f58.png">

The import into Terraform went fine and we have the following config where we have wrapped the fivetran_connector Terraform resource with our own module:
<img width="717" alt="image" src="https://user-images.githubusercontent.com/111284232/232987804-9711387c-55e7-42ff-a0dd-2b04c8e96b08.png">

When I run terraform plan after the import the plan shows me that Terraform wants to add the update method which does not make sense to me. I would have perhaps understood if Terraform would show that the update method was changing from X to NATIVE_UPDATE and so I had configure the wrong update_method in my Terrafrom config. I looked at the Terraform state for my imported connector but I could not find any info there on update_method so it seems like like the update_method is not being transferred into the Terraform state when I run the import.

<img width="606" alt="image" src="https://user-images.githubusercontent.com/111284232/232988200-ca1ba377-76d6-4dc6-b793-49d2ede91b89.png">

**Comment by kloveday2** [comment]
I am experiencing a similar issue. After creating a SQL connector with 
          update_method = "NATIVE_UPDATE"
 Any subsequent plans want to update the connector to the same thing again.
 
When I query the API, it is saying my connector is
            "update_method": "Standard",
 'Standard' is not an option for the terraform config. This mismatch is probably causing it to repeatedly want to update the resource back to NATIVE_UPDATE
 
 Applying this does not make any change to the connector and it will continue to show up on new plans.

**Comment by beevital** [comment]
Opened internal ticket for this.
Considering this as a bug

**Comment by beevital** [comment]
Fix on API side merged, once it will be deployed to production TF provider will work correctly.
