### ISSUE TITLE
CosmosDB support

### ISSUE THREAD

**Issue by chrisluedtke** [fivetran/terraform-provider-fivetran#117]
I searched the project for "cosmos" and see no mention of it. If this connector is supported, I'm wondering how the config arguments map to [the REST API](https://fivetran.com/docs/rest-api/connectors/config#cosmosdb).

**Comment by beevital** [comment]
Yes, there is no mapping for cosmos fields yes. We will add it soon.

**Comment by beevital** [comment]
Support for CosmosDB connector will be included in v0.7.2
PR to track changes: https://github.com/fivetran/terraform-provider-fivetran/pull/159
