### ISSUE TITLE
S3 connector produces a diff related to list_strategy

### ISSUE THREAD

**Issue by Israphel** [fivetran/terraform-provider-fivetran#123]
In recent versions of the provider I'm getting a diff on every plan:

`list_strategy            = "complete_listing" -> null`

My module code doesn't include that line:

```terraform
# Fivetran S3 connector
resource "fivetran_connector" "s3" {
  group_id          = var.group_id
  service           = "s3"
  sync_frequency    = var.sync_frequency
  paused            = var.paused
  pause_after_trial = false

  destination_schema {
    name  = var.destination_schema.name
    table = var.destination_schema.table
  }

  config {
    bucket   = var.bucket_name
    prefix   = var.folder
    role_arn = aws_iam_role.iam_role.arn
  }
}
```

what is it for and why is it mandatory now? the [documentation](https://registry.terraform.io/providers/fivetran/fivetran/latest/docs/resources/connector) for the resource doesn't mention what it does or what it is for.

**Comment by beevital** [comment]
This is a bug.
