### ISSUE TITLE
Order is not preserved across multiple terraform plan

### ISSUE THREAD

**Issue by drorasaf** [fivetran/terraform-provider-fivetran#130]
Fivetran provider version 0.6.19
Terraform version: 1.4.6

The resources.tf file has a resource `fivetran_connector` with `custom_tables` inside config with multiple fields.
After running `terraform apply`, the next iteration: `terraform plan` results in changes.
After a short investigation that there is a set which is not preserving an order being used. Which cause the changes in the list of the fields.
My understanding is that this line does not preserve any order which is the root for this problem:
https://github.com/fivetran/terraform-provider-fivetran/blob/main/fivetran/resource_connector.go#L1080

**Comment by beevital** [comment]
This issue will be fixed in the next upcoming release

**Comment by drorasaf** [comment]
Thanks for solving this, I have validated it is working on the latest

**Comment by trunsky** [comment]
fyi this issue reappeared for me when upgrading to v1.0.0
