### ISSUE TITLE
Missing support for snowflake as source connector

### ISSUE THREAD

**Issue by kristian-petersen** [fivetran/terraform-provider-fivetran#133]
Looks like the provider doesnt support Snowflake as source connectors currently in Beta.  Schema block isnt really applicable for this connector type.

` Error: Insufficient destination_schema blocks
│ 
│   on ../../terraform_modules/snowflake_connector_module/snowflake_connector.tf line 6, in resource "fivetran_connector" "snowflake_connector":
│    6: resource "fivetran_connector" "snowflake_connector" {
│ 
│ At least 1 "destination_schema" blocks are required.
╵
╷
│ Error: Unsupported argument
│ 
│   on ../../terraform_modules/snowflake_connector_module/snowflake_connector.tf line 15, in resource "fivetran_connector" "snowflake_connector":
│   15:     schema_prefix            = var.schema_prefix
│ 
│ An argument named "schema_prefix" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on ../../terraform_modules/snowflake_connector_module/snowflake_connector.tf line 16, in resource "fivetran_connector" "snowflake_connector":
│   16:     auth                     = var.auth
│ 
│ An argument named "auth" is not expected here. Did you mean "path"?
╵
╷
│ Error: Unsupported argument
│ 
│   on ../../terraform_modules/snowflake_connector_module/snowflake_connector.tf line 23, in resource "fivetran_connector" "snowflake_connector":
│   23:     passphrase               = var.passphrase
│ 
│ An argument named "passphrase" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on ../../terraform_modules/snowflake_connector_module/snowflake_connector.tf line 25, in resource "fivetran_connector" "snowflake_connector":
│   25:     is_private_key_encrypted = var.is_private_key_encrypted
│ 
│ An argument named "is_private_key_encrypted" is not expected here.`

**Comment by beevital** [comment]
We have prepared Open API Schema based connector resource with dynamically built schema for connector configs. So the fields will be available to manage via terraform in next upcoming release

**Comment by LukaDevic** [comment]
Fixed in latest provider release - v0.7.0

@kristian-petersen please download latest version v0.7.0 to be able to use reported previously missing fields.

Closing this issue

**Comment by beevital** [comment]
Support for Snowflake DB connector will be included into v0.7.2 

PR to track changes: https://github.com/fivetran/terraform-provider-fivetran/pull/159
