### ISSUE TITLE
resource to unpause a connector?

### ISSUE THREAD

**Issue by willwdunlap** [fivetran/terraform-provider-fivetran#155]
Hi all, the documentation conveys that when creating a new connector and adding a schema you should instantiate it in a paused state so that it doesn't sync before getting the schema config.  And then once schema config has been updated the connector should be unpaused.

However, it's unclear what resource to use to unpause the connector.  In the [code example](https://github.com/fivetran/terraform-provider-fivetran/blob/main/examples/resources/resource_connector/connector_schema_setup.tf), it uses a 'fivetran_connector_schedule' but there's no documentation regarding this resource and when I try to create this resource, terraform doesn't recognize it as a valid resource.

Insights appreciated!

**Comment by beevital** [comment]
Hey @willwdunlap !
Please check latest v0.7.2-pre version.

https://registry.terraform.io/providers/fivetran/fivetran/latest/docs/resources/connector_schedule
