### ISSUE TITLE
fivetran_connector_schema_config: enable wildcards for schema, table, and column matching

### ISSUE THREAD

**Issue by ann8ty** [fivetran/terraform-provider-fivetran#161]
for example, I have an AWS dynamo db table that looks like:

```
env-context-uniqueid
```

in the terraform, I would like to use a wildcard, or regex, or something for the uniqueid so I can specify it in code without knowing the unique id

```
resource "fivetran_connector_schema_config" "schema" {
  connector_id = fivetran_connector.dynamo_connector.id
  schema_change_handling = "BLOCK_ALL" 
  schema {
    name = "env_dynamodb_raw"
    table {
      name = "env-context-*"
      enabled = true
}}}
```

**Comment by beevital** [comment]
This is a good idea, but it is possible only for tables level, not for columns.

**Comment by ann8ty** [comment]
follow up info.  this continued to work in v1.0.0 but when i tried to go to v1.1.0 the dynamic tables no longer work.

**Comment by ann8ty** [comment]
yeah it looks like v1.0.1 broke this code, and v1.0.2 did not fix it.
