### ISSUE TITLE
Missing schema_prefix field for MongoDB connector 

### ISSUE THREAD

**Issue by mars-lan** [fivetran/terraform-provider-fivetran#165]
I tried to use the following Terraform code to create a MongoDB connector based on the [API documentation](https://fivetran.com/docs/rest-api/connectors/config#mongodb): 

```
resource "fivetran_connector" "mongo" {
  group_id          = fivetran_group.metaphor.id
  service           = "mongo"

  destination_schema {
    name = "<name>"
  }

  config {
    hosts           = ["<host>"]
    schema_prefix   = "<prefix>"
  }
}
```

However, Terraform returned the following error:

```
╷
│ Error: Unsupported argument
│ 
│   on modules/fivetran/main.tf line 47, in resource "fivetran_connector" "mongo":
│   47:     schema_prefix   = "<redacted>"
│ 
│ An argument named "schema_prefix" is not expected here.
╵
```

If I remove `schema_prefix` and apply the change, the API returns the following error:

```
╷
│ Error: create error
│ 
│   with module.fivetran.fivetran_connector.mongo,
│   on modules/fivetran/main.tf line 33, in resource "fivetran_connector" "mongo":
│   33: resource "fivetran_connector" "mongo" {
│ 
│ status code: 400; expected: 201; code: InvalidInput; message: Field 'schema_prefix' is required
╵
```

**Comment by beevital** [comment]
You should define schema_prefix inside `destination_schema` block:
```
resource "fivetran_connector" "mongo" {
  group_id          = fivetran_group.metaphor.id
  service           = "mongo"

  destination_schema {
    prefix = "<prefix>"
  }

  config {
    hosts           = ["<host>"]
  }
}
```

https://registry.terraform.io/providers/fivetran/fivetran/0.7.1/docs/resources/connector#nested-schema-for-destination-schema

**Comment by mars-lan** [comment]
@beevital please reopen this issue as it's not resolved.

`schema_prefix` is a specific (and required) config option for `mongo` connector. See  [API documentation](https://fivetran.com/docs/rest-api/connectors/config#mongodb). Not specifying it results in the error above. It's different from `destination_schema.prefix`, or at least the TF module doesn't translate that properly. Please give it a try and you shall see what I meant.

**Comment by mars-lan** [comment]
The same issue for Postgres connector (e.g. `postgres_rds`):

```
╷
│ Error: create error
│ 
│   with module.fivetran.fivetran_connector.postgres,
│   on modules/fivetran/main.tf line 46, in resource "fivetran_connector" "postgres":
│   46: resource "fivetran_connector" "postgres" {
│ 
│ status code: 400; expected: 201; code: InvalidInput; message: Field 'schema_prefix' is required
╵
```

**Comment by mars-lan** [comment]
My bad. Didn't read the documentation properly. https://github.com/fivetran/terraform-provider-fivetran/issues/165#issuecomment-1648081539 works as advertised.
