### ISSUE TITLE
Incorrect docs on fivetran_group_connectors

### ISSUE THREAD

**Issue by LGAnyVan** [fivetran/terraform-provider-fivetran#169]
https://registry.terraform.io/providers/fivetran/fivetran/latest/docs/data-sources/group_connectors

Title and usage copied and not updated from https://registry.terraform.io/providers/fivetran/fivetran/latest/docs/data-sources/group_users
> Data Source: fivetran_group_users
This data source returns a list of information about all users within a group in your Fivetran account.

> [Example Usage](https://registry.terraform.io/providers/fivetran/fivetran/latest/docs/data-sources/group_connectors#example-usage)
data "fivetran_group_users" "group_users" {
        id = "anonymous_mystery"
}

**Comment by beevital** [comment]
https://github.com/fivetran/terraform-provider-fivetran/pull/171

**Comment by beevital** [comment]
Fix merged, docs will be updated with next release.
