### ISSUE TITLE
Cannot import existing connector schedule

### ISSUE THREAD

**Issue by LGAnyVan** [fivetran/terraform-provider-fivetran#170]
Cannot import existing connector schedule. Have tried for existing and new connectors, plus many permutation of what Fivetran could perceive as the connector IDs. 

Either the data is not exposed via API, or the [docs](https://registry.terraform.io/providers/fivetran/fivetran/latest/docs/resources/connector_schedule) are misleading.

```
terraform import fivetran_connector_schedule.microsoft_ads_schedule "bingads"
fivetran_connector_schedule.microsoft_ads_schedule: Importing from ID "bingads"...
fivetran_connector_schedule.microsoft_ads_schedule: Import prepared!
  Prepared fivetran_connector_schedule for import
fivetran_connector_schedule.microsoft_ads_schedule: Refreshing state... [id=bingads]
╷
│ Error: Connector with id = doesn't exist.
│
│ status code: 405; expected: 200; code: Error; message: HTTP 405 Method Not Allowed
```

_Note: bingads is used in place of the actual connector_id for anonymity_

**Comment by beevital** [comment]
@LGAnyVan you don't need to import this resource. 
If you already have an existing connector with id = `my_connector_id` just define `fivetran_connector_schedule` resource for it:

```hcl
resource "fivetran_connector_schedule" "my_connector_schedule" {
    connector_id = "my_connector_id"

    sync_frequency     = "360"
    paused             = false
    pause_after_trial  = true
    schedule_type      = "auto"
}
```

Docs will be updated in next release.

**Comment by beevital** [comment]
To fetch schedule values from existing connector use `fivetran_connector` data source:
```hcl
data "fivetran_connector" "my_connector" {
    id = "my_connector_id"
}

# now you can use schedule values from this data_source:
#   sync_frequency = data.fivetran_connector.my_connector.sync_frequency
#   paused = data.fivetran_connector.my_connector.paused
```
