### ISSUE TITLE
Suspicious File Report on Fivetran Provider exe 0.7.1

### ISSUE THREAD

**Issue by jifeous** [fivetran/terraform-provider-fivetran#174]
Our firewall is identifying the latest update terraform-provider-fivetran_v0.7.1.exe as suspicious:
Contains Sections with size discrepancies
Invalid Checksum
Non-standard section names

Anyone else having this problem?

**Comment by beevital** [comment]
Hey @jifeous, it's strange that you've faced this issue. Does it identifying v0.7.2/v0.7.3 the same way?

v0.7.1 may really have invalid checksum because it was released not from the HEAD commit in main but from manually added tag. I suspect this could be some bug in go-releaser.

**Comment by jifeous** [comment]
We never had an issue with any previous update, we're currently pinned to 0.7.1 but 0.7.2 works fine

**Comment by beevital** [comment]
@jifeous could you try [v1.0.1](https://registry.terraform.io/providers/fivetran/fivetran/1.0.1) - does it reports also?
It seems to me that it's a false alarm. 

v0.7.1 was released as usual with hashicorp-provided toolchain.
