### ISSUE TITLE
fivetran_connector doesn't support timeouts

### ISSUE THREAD

**Issue by bosmak** [fivetran/terraform-provider-fivetran#182]
**Describe the bug**
I can't run some connectors using `run_setup_tests` because the test takes more than 10 minutes to test.

**To Reproduce**
Just create a regular connector that takes more than 10 minutes to test.

**Expected behavior**
I should be able to set a timeout to the resource to allow a bigger time slot for the resource.
https://developer.hashicorp.com/terraform/language/resources/syntax#operation-timeouts

**Logs & Output**
Not relevant

**Comment by beevital** [comment]
Fixed in v1.0.0
Added custom timeouts for connector create/update operations
