### ISSUE TITLE
Inputs "paused" and "pause_after_trial" are gone from latest versions of provider

### ISSUE THREAD

**Issue by anderskotsalaineneqt** [fivetran/terraform-provider-fivetran#195]
**Describe the bug**
Hi,
I had previous issue using Fivetran TF provider to set up a GCP mysql connector (https://github.com/fivetran/terraform-provider-fivetran/issues/115). I was happy to find out that the issue had been solved in a later release of the Fivetran provider so I upgraded my Fivetran provider to version 0.7.3 to be able to use the mysql config parameter "replica_id". To my surprise I suddenly got a bunch of errors for existing connectors that I had Terraformed stating that the argument "paused" and "pause_after_trial" are unsupported. I looked through the documentation for the newer releases of the Terraform provider but none of them mention these arguments which can be found in release [0.6.15](https://registry.terraform.io/providers/fivetran/fivetran/0.6.15/docs/resources/connector). It seems like they somehow have been removed and this seems like a bug as it's a breaking change.

**To Reproduce**
Use Fivetran provider version 0.7.3 and try setting a fivetran connector that looks like this. I'm setting up my Fivetran connector in a module we have created and that is why the values provided are coming as variables.

````
resource "fivetran_connector" "cloudsql" {
  group_id           = data.fivetran_destination.destination.group_id
  service            = var.db_type
  sync_frequency     = var.sync_frequency_min
  run_setup_tests    = true
  trust_fingerprints = var.trust_fingerprints
  trust_certificates = var.trust_certificates
  paused             = var.paused
  pause_after_trial  = false

  destination_schema {
    prefix = var.schema_prefix
  }

  config {
    host             = var.host
    port             = var.host_port
    database         = var.host_database
    user             = var.host_database_user
    password         = data.google_secret_manager_secret_version.db-user-password-secret.secret_data
    tunnel_host      = var.ssh_tunnel_host
    tunnel_port      = var.ssh_tunnel_port
    tunnel_user      = var.ssh_tunnel_user
    update_method    = var.update_method
    replication_slot = var.replication_slot
    publication_name = var.publication_name
    replica_id       = var.replica_id
  }
}
````

**Expected behavior**
The arguments paused and pause_after_trial should be available to be used in all versions versions  up to 1.0.0. If they are then removed in 1.0.0 that should be made clear in the provider documentation

**Comment by beevital** [comment]
@anderskotsalaineneqt use "fivetran_connector_schedule" resource to manage connector schedule:
https://registry.terraform.io/providers/fivetran/fivetran/latest/docs/resources/connector_schedule
