### ISSUE TITLE
Facebook ads authentication request

### ISSUE THREAD

**Issue by drorasaf** [fivetran/terraform-provider-fivetran#206]
**Is your feature request related to a problem? Please describe.**
Currently, I am unable to connect via system user token through terraform. so I currently set up all of the schema on terraform, then invoke it, edit it manually, then invoke again to fix the schema.
In fivetran dashboard, when creating a new connector, of type facebook ads, there are two authentication options, the first is to use a user to authorize it which is user_access_token as can be found at the config. However, the second one is system user token, which does not exist as part of the config. 

**Describe the solution you'd like**
Add the system user token as a field in facebook_ads config

**Describe the use-cases if possible**
Programmatically use system user token for multiple accounts, to avoid coupling of connectors to specific user, as users can change over time but the system account is fixed.

**Comment by beevital** [comment]
Currently we do not support this way of Authorization for Facebook Ads.
https://fivetran.com/docs/rest-api/connectors/config#authorization_104

You can file a Feature request on our [support portal](support.fivetran.com) for that

As per `user_access_token` field - as we use shared set of connector config fields in schema - it is represented, but it is used by another service type.
