### ISSUE TITLE
fivetran_connector_schedule: Error: Connector with id =ID doesn't exist.

### ISSUE THREAD

**Issue by tobiasrummelsberger** [fivetran/terraform-provider-fivetran#213]
**Describe the bug**
When creating a connector_schedule the following error is raised. The connector with the ID "speed_royalty" exists, a connector with the id "=speed_royalty" does not exist.

```
│ Error: Connector with id =speed_royalty doesn't exist.
│ 
...
│ 
│ json: cannot unmarshal array into Go struct field
│ ConnectorConfigResponse.data.config.servers of type string; code: Success;
│ message: 
```

**To Reproduce**
```
resource "fivetran_connector_schedule" "confluent_cloud_connector_schedule" {
  connector_id      = "speed_royalty"
  sync_frequency    = "15"
  paused            = false
  pause_after_trial = false
  schedule_type     = "auto"
}
```

**Expected behavior**
The resource should be created and the schedule of the resource adjusted accordingly.

**Logs & Output**
`terraform plan` is successful. The error is only raised when applying.
```
│ Error: Connector with id =speed_royalty doesn't exist.
│ 
│   with module.mart["pod_shipment_opportunities_ingestion"].module.fivetran_confluent_cloud_connector[0].fivetran_connector_schedule.confluent_cloud_connector_schedule,
│   on ../modules/fivetran_confluent_cloud_connector/main.tf line 24, in resource "fivetran_connector_schedule" "confluent_cloud_connector_schedule":
│   24: resource "fivetran_connector_schedule" "confluent_cloud_connector_schedule" {
│ 
│ json: cannot unmarshal array into Go struct field
│ ConnectorConfigResponse.data.config.servers of type string; code: Success;
│ message: 
```

**Plugin version:**
version 1.1.1

**Comment by beevital** [comment]
@tobiasrummelsberger are you sure that the targeted connector really exists?

**Comment by beevital** [comment]
Mayve the error in id, or wrong account API key used

**Comment by beevital** [comment]
What type of connector is it? It seems like the bug in our code with data mappings

**Comment by beevital** [comment]
Figured out the problem. Will fix it in nearest release.

**Comment by beevital** [comment]
https://github.com/fivetran/terraform-provider-fivetran/pull/224 PR with a fix

**Comment by beevital** [comment]
Fix released
