### ISSUE TITLE
Fivetran group gets created before Fivetran Service Account gets available

### ISSUE THREAD

**Issue by NemanjaMilenkovic** [fivetran/terraform-provider-fivetran#215]
**Describe the bug**
Fivetran group gets created but Fivetran Service Account is not immediately available - this cause resources that depend on fivetran_group.service.account to proceed without resource being fully created and fail on trying to use the Fivetran Service Account.

Currently available workaround would be to add a delay after creating fivetran group OR to repeat terraform apply after first failed attempt.

**To Reproduce**

```terraform
resource "fivetran_group" "group" {
    name  = "MyGroup"
}

resource "google_storage_bucket_iam_member" "fivetran_source_bucket_iam" {
  role = local.fivetran_sa_gcp_gcs_role
  member  = `serviceAccount:g-${replace(fivetran_group.customer_user_group.id, "_", "-")}@fivetran-production.iam.gserviceaccount.com`
  depends_on = [fivetran_group.customer_user_group, fivetran_destination.big_query]
}
```

**Expected behavior**
Fivetran Group is created when Fivetran Service Account is fully created as well.

**Logs & Output**
```terraform
Error: Request `Create IAM Members roles/bigquery.user serviceAccount:g-similar-theory@fivetran-production.iam.gserviceaccount.com for project "test-1"` returned error: Batch request and retried single request "Create IAM Members roles/bigquery.user serviceAccount:g-similar-theory@fivetran-production.iam.gserviceaccount.com for project \"test-1\"" both failed. Final error: Error applying IAM policy for project "test-1": Error setting IAM policy for project "test-1": googleapi: Error 400: Service account g-similar-theory@fivetran-production.iam.gserviceaccount.com does not exist., badRequest

resource "fivetran

```

**Plugin version:**
Fivetran Terraform Provider version: 1.1.1

**Additional context**
n/a

**Comment by beevital** [comment]
Service account won't be created until at least one depending resource is created. 
BUT we have a new endpoint that enforces this and provides service account directly:
https://fivetran.com/docs/rest-api/groups#retrievegroupserviceaccount

I have currently planned task to support it in Terraform. I hope this will be included in nearest release.
The logic will be the following:
- Once group is created - group_resource will make a request to retrieve service account.
- This call will force SA to be initialised.

Currently you should open Destination/Connector setup form to force this process. Or manually call API endpoint.

**Comment by NemanjaMilenkovic** [comment]
Thank you!

**Comment by beevital** [comment]
Now you can use https://registry.terraform.io/providers/fivetran/fivetran/latest/docs/data-sources/group_service_account to retrieve service account for a group.
The fact that this data source will make the request will force us to init service account for the group.

**Comment by NemanjaMilenkovic** [comment]
@beevital Great! Thank you!
