### ISSUE TITLE
Email connector, setup tests don't succeed without manual intervention

### ISSUE THREAD

**Issue by lucasespinos** [fivetran/terraform-provider-fivetran#223]
**Describe the bug**
When setting up the email connector, I have to go to the UI to edit and save the connection (though without actually changing anything) forcing sending an email in order to make the connection.

```
resource "fivetran_connector" "email_inventory_on_handy" {
    group_id = fivetran_group.group.id
    service = "email"
    run_setup_tests = true
    destination_schema {
      name = google_bigquery_dataset.wp_dataset.dataset_id
      table = google_bigquery_table.inventory_on_hand.table_id
    }

    config {
        connection_type = "Directly"
        pattern = "Inventoryonhand\\-csv\\-.+\\.csv"
        skip_after = 0
        json_delivery_mode = "Packed"
        skip_before = 0 
        empty_header = true
        file_type = "csv"
        compression = "infer"
    }

    depends_on = [
        fivetran_destination.bigquery_destination
    ]
}

resource "fivetran_connector_schedule" "email_inventory_on_handy_schedule" {
    connector_id = fivetran_connector.email_inventory_on_handy.id
    daily_sync_time = "10:00"
    sync_frequency = 1440
    paused = false 
    pause_after_trial = false
}

resource "fivetran_connector_schema_config" "inventory_on_hand_schema" {
  connector_id = fivetran_connector.email_inventory_on_handy.id
  schema_change_handling = "BLOCK_ALL"
  schema {
    name = google_bigquery_dataset.wp_dataset.dataset_id
    table {
      name = google_bigquery_table.inventory_on_hand.table_id
      column {
        name = "column_0"
        enabled = "true"
      }
      column {
        name = "column_1"
        enabled = "true"
      }
      column {
        name = "column_2"
        enabled = "true"
      }
      column {
        name = "column_3"
        enabled = "true"
      }
      column {
        name = "column_4"
        enabled = "true"
      }
      column {
        name = "column_5"
        enabled = "true"
      }
      column {
        name = "column_6"
        enabled = "true"
      }
      column {
        name = "column_7"
        enabled = "true"
      }
      column {
        name = "column_8"
        enabled = "true"
      }
      column {
        name = "column_9"
        enabled = "true"
      }
    }
  }
}
```

**Logs & Output**
```
Error: create
│
│   with fivetran_connector_schema_config.inventory_on_hand_schema,
│   on connectors.tf line 37, in resource "fivetran_connector_schema_config" "inventory_on_hand_schema":
│   37: resource "fivetran_connector_schema_config" "inventory_on_hand_schema" {
│
│ status code: 400; expected: 200; code: InvalidInput; message: We expected the connector's setup state ('status.setup_state') to
│ be 'connected', but it was 'incomplete'.
│ Please configure the connector and perform the connector setup tests.
```

**Plugin version:**
1.0.0

**Comment by lucasespinos** [comment]
Tried on version 1.1.1 but still same error

**Comment by beevital** [comment]
Hi @lucasespinos 
I was trying to reproduce your case and created connector with exact configuration you've provided. It doesn't passes one of the setup tests. In UI on the dashboard I have exactly the same output.

[Connector setup guide](https://fivetran.com/docs/files/email/setup-guide)  states that for successful setup you'll have to send a email with attachement before finishing installation.

I understand that this brake the flow for terraform - you can't know group_id before `apply`. Otherwise you'll have to apply twice
- Step 1: create group resource an apply to retrieve group_id
- Step 2: send example email to `group_id.schema_name@email-connector.fivetran.com` 
- Step 3: apply the rest configuration 

I totally agree that this is poor WA.

I'll try to reach out to connector team to try to update the tests flow, or make attachment test optional to be able to setup connector smoothly.

**Comment by lucasespinos** [comment]
Hey @beevital 

Yes we can think about separate deployments for group and the rest of connectors and add some automation to automatically send the email for setup tests but still for me looks a bit of a hack.
But agree with you will be nice to have an option to make setup tests optional.

**Comment by beevital** [comment]
I've reached out to team that maintains email connector and proposed to make the test optional. This could be a solution in such cases - if you're sure that your sender tweaked correctly.

But in worst case - connector will just work "OK", but data sent to it will be just lost.

**Comment by beevital** [comment]
There's no solution still from connector maintainers team. 
I have to close the issue for now.
