### ISSUE TITLE
Beta Designation

### ISSUE THREAD

**Issue by marcusinthesky** [fivetran/terraform-provider-fivetran#230]
Is this code base still in Beta, as per the documentation:
```
NOTE: terraform-provider-fivetran is in [BETA](https://en.wikipedia.org/wiki/Software_release_life_cycle#Beta) development stage. Future versions may introduce minor changes and bug-fixes.
```
since the V1.0 release back in August.

**Comment by beevital** [comment]
Hey @marcusinthesky!
Looks like we just forget to cleanup readme file.
V1.0.0 means that we have passed beta stage and we won't introduce further breaking changes for existing resources.
