### ISSUE TITLE
Cannot manage in Terraform the multiple roles that definable in UI

### ISSUE THREAD

**Issue by LeoTheGriff** [fivetran/terraform-provider-fivetran#234]
**Describe the bug**
Cannot manage in Terraform the multiple roles that definable in UI.
How do you set multiple roles to a user at different levels? e.g. account billing and destination analyst

I don't see from the docs how this can be described in existing resources. You [can set a role with a user](https://registry.terraform.io/providers/fivetran/fivetran/latest/docs/resources/user), but it is a string not a list. 

<img width="1159" alt="image" src="https://github.com/fivetran/terraform-provider-fivetran/assets/9199543/3341feb6-3377-4f66-8bf0-c6fcc12e41d4">

**To Reproduce**
Provide an example .tf configuration 

In UI: create user with an account role and a destination role. 

**Expected behavior**

Roles as an array or another resource mapping roles to users

**Logs & Output**
Provide terraform CLI output on `plan` | `apply`. If it is possible, please, refer to [this guide](https://developer.hashicorp.com/terraform/internals/debugging) to enable debug output.

**Plugin version:**
Please specify Fivetran Terraform Provider version you are using.

**Additional context**

Workaround is to remove destination-specific role and rely on `<inherited>`

**Comment by beevital** [comment]
@LeoTheGriff have you tried to use https://registry.terraform.io/providers/fivetran/fivetran/latest/docs/resources/team_group_membership ?

**Comment by beevital** [comment]
In API we have slightly different approach. 
User may have only one role on account level. 
For each resource you have to assign role separately by adding user memberships in reaources

**Comment by LeoTheGriff** [comment]
> https://registry.terraform.io/providers/fivetran/fivetran/latest/docs/resources/team_group_membership
I am not on the enterprise license so I cannot use teams.

> For each resource you have to assign role separately by adding user memberships in resources
How do Ido this?

**Comment by beevital** [comment]
> How do I do this?

https://fivetran.com/docs/rest-api/users#connectormemberships - for connectors
https://fivetran.com/docs/rest-api/users#groupmemberships - for destinations

But looks like these endpoints are not covered by TF provider. We will do that ASAP)

**Comment by LeoTheGriff** [comment]
Awesome, thank you!

**Comment by fivetran-aleksandrboldyrev** [comment]
https://github.com/fivetran/terraform-provider-fivetran/releases/tag/v1.1.19
