### ISSUE TITLE
SshTunnel Vs SSHTunnel

### ISSUE THREAD

**Issue by mcwata7** [fivetran/terraform-provider-fivetran#253]
**Describe the bug**
fivetran_destination always requires update when using SSHTunnel (SshTunnel vs SSHTunnel). State file saves as SSHTunnel but the attributes enum is SshTunnel.

**To Reproduce**
```
resource "fivetran_destination" "this" {
...
  config {
    connection_type = "SSHTunnel"
...
  }
}
```

**Expected behavior**
Either the state file should save as SshTunnel or enum should change to SSHTunnel.

**Comment by beevital** [comment]
Unfortunately for different destinations API side returns different values (for some "SshTunnel" and for others "SSHTunnel")
I think we can handle it in special way. Thank you for reporting this, we will try to introduce some unified solution.

**Comment by beevital** [comment]
I can't find any mention of `SSHTunnel` in our public docs for API or in our latest terraform provider public docs.
I've tested several different configs for various destinations with SshTunnel and everything works as expected. 
No drifting changes, state consistent with config. So I wasn't able to reproduce the issue.

Could you please specify what service caused the issue?
