### ISSUE TITLE
Cloud provider is missing in destination config

### ISSUE THREAD

**Issue by ktadiko** [fivetran/terraform-provider-fivetran#275]
**Describe the bug**
I'm trying to setup databricks destination. the destination config is missing required attribute `cloud_provider`.

**To Reproduce**
```
resource "fivetran_destination" "dest" {
    group_id = fivetran_group.group.id
    service = "databricks"
    time_zone_offset = "0"
    region = "US_EAST_1"
    run_setup_tests = "true"

    config {
        host = "destination.fqdn"
        port = 443
        personal_access_token = "foobar"
        catalog = "dev"
        connection_type = "Directly"
        http_path = "sql/protocolv1/o/2873663545782684434-15262-272625-fives565",
        cloud_provider = "AWS" ----> missing
    }
}
```

**Expected behavior**
cloud_provider must be part of config

The go-fivetran sdk is missing cloud provider in destionation config. I realized a little late external contributions are not accepted. 

Support ticket: https://support.fivetran.com/hc/en-us/requests/193650

**Comment by beevital** [comment]
@ktadiko thank you, will fix it in next release for sure. Looks like the field is missing in Open API Schema. 
We will update it and include changes in next release.

**Comment by beevital** [comment]
@ktadiko what version you are on? It is included into the lates version: https://registry.terraform.io/providers/fivetran/fivetran/latest/docs/resources/destination#cloud_provider

**Comment by beevital** [comment]
>The go-fivetran sdk is missing cloud provider in destionation config.
We do not use go-fivetran SDK config structure since version 0.7.2 BTW, so it can't be an issue .

**Comment by beevital** [comment]
in fivetrna-sdk we have now custom config for destinations, so we pass it as map[string]interface{} without any strict mapping. We use this approach to be able to support new fields in terraform without sdk changes.

**Comment by ktadiko** [comment]
> @ktadiko what version you are on? It is already included into the latest version: https://registry.terraform.io/providers/fivetran/fivetran/latest/docs/resources/destination#cloud_provider

Ah! I was using 1.1.15. Will upgrade thanks!
