### ISSUE TITLE
Connector throws inconsistent result in tf-cloud

### ISSUE THREAD

**Issue by IkeHull** [fivetran/terraform-provider-fivetran#278]
I get this error message from an "apply" run using TF-cloud

--
Error: Provider produced inconsistent result after apply
When applying changes to fivetran_connector.connector_fivetran_log, provider "provider[\"registry.terraform.io/fivetran/fivetran\"]" produced an unexpected new value: .config: was absent, but now present.

This is a bug in the provider, which should be reported in the provider's own issue tracker.
--
TF code looks like this

resource "fivetran_destination" "destination" {
  group_id         = fivetran_group.group.id
  region           = var.fivetran_region
  run_setup_tests  = false
  service          = "big_query"
  time_zone_offset = var.fivetran_time_zone_offset

  config {
    project_id = random_id.cm-project-id.hex
    data_set_location = var.fivetran_data_set_location
  }
}

 resource "fivetran_connector" "connector_fivetran_log" {
     group_id = fivetran_group.group.id
     service = "fivetran_log"

     destination_schema {
         name = "fivetran_log"
     }
 }

---
TF version in cloud setup is 1.7.5
provider version is 1.1.17

**Comment by beevital** [comment]
@IkeHull as a WA just define `config` block for a connector.
Looks like side-effect of import fix.

**Comment by AaronCoquet-Easypark** [comment]
I have a similar / the same issue with an SQL Server connection that I'm trying to import.
Output:
> Error: Provider produced inconsistent result after apply
> When applying changes to fivetran_connector.ext_<redacted>, provider "provider[\"registry.terraform.io/fivetran/fivetran\"]" produced an unexpected new value: .config.username: was cty.StringVal(<redacted>), but now null.
> This is a bug in the provider, which should be reported in the provider's own issue tracker.

Code that produced this:
```hcl
resource "fivetran_connector" "ext_<redacted>" {
  group_id        = <redacted>
  run_setup_tests = false
  service         = "sql_server"

  config {
    update_method = "TELEPORT"
    database = <redacted>
    password = <redacted>
    port     = <redacted>
    host     = <redacted>
    username = <redacted>
  }

  destination_schema {
    prefix = <redacted>
  }
}
```
I'm not sure if it matters, but the `terraform plan` shows this:
![image](https://github.com/fivetran/terraform-provider-fivetran/assets/110165637/609cba21-cc42-426a-a1a1-322658d29fa2)

TF version: Terraform v1.7.5 on darwin_arm64
+ provider registry.terraform.io/fivetran/fivetran v1.1.19

**Comment by beevital** [comment]
@AaronCoquet-Easypark that's another one. I'll take a look. From what version you're upgrading?

**Comment by beevital** [comment]
Looks like a problem with sql_server API response. It doesn't return `username` for some reason and it came empty into state.
Let me dig into it.

**Comment by beevital** [comment]
And the most important - why are you're using `username` field? 
You should use just `user`.
https://registry.terraform.io/providers/fivetran/fivetran/latest/docs/resources/connector#user
What is happening:
- You've defined `username` in your resource definition and provider sends it in request
- API doesn't expect field `user` for service `sql_server` and just ignores it
- Terraform receives response with `user` field null and without `username` - so it set's it to `null` in state and returns an error

**Comment by beevital** [comment]
@AaronCoquet-Easypark you need to update your config the following way:
```
resource "fivetran_connector" "ext_<redacted>" {
  group_id        = <redacted>
  run_setup_tests = false
  service         = "sql_server"

  config {
    update_method = "TELEPORT"
    database = <redacted>
    password = <redacted>
    port     = <redacted>
    host     = <redacted>
    user = <redacted>
  }

  destination_schema {
    prefix = <redacted>
  }
}

**Comment by AaronCoquet-Easypark** [comment]
Thanks for all the feedback, and the expected updates!
