### ISSUE TITLE
Gong and Postmark Connectors

### ISSUE THREAD

**Issue by petero2024** [fivetran/terraform-provider-fivetran#287]
**Describe the bug**
Gongio and Postmark connectors return an error when Terraform provisioning Fivetran connector resources with credentials.

Please also note that the GongIo part of the documentation lists username, password as well as access_key, access_key_secret authentication. My understanding is that 3 input is needed on the Fivetran dashboard 1) access_key 2) access_key_secret  and 3) base_url.

**To Reproduce**
GiongIo connector:

resource "fivetran_connector" "gongio" {
  group_id    = module.fivetran_destination.fivetran_destination_group_id
  service     = "gongio"
  run_setup_tests = true

  destination_schema {
        name = "ft_gongio"
    }

  config {
      username = var.fivetran_connector_gong_access_key
      password = var.fivetran_connector_gong_client_secret
      base_url = var.fivetran_connector_gong_base_url
  }
}

OR

resource "fivetran_connector" "gongio" {
  group_id    = module.fivetran_destination.fivetran_destination_group_id
  service     = "gongio"
  run_setup_tests = true

  destination_schema {
        name = "ft_gongio"
    }

  config {
      accesskey = var.fivetran_connector_gong_access_key
      access_key_secret = var.fivetran_connector_gong_client_secret
      base_url = var.fivetran_connector_gong_base_url
  }
}

Postmark connector:

resource "fivetran_connector" "postmark" {
  group_id    = module.fivetran_destination.fivetran_destination_group_id
  service     = "postmark"
  run_setup_tests = true

  destination_schema {
        name = "ft_postmark"
    }

  config {
      api_key = var.fivetran_connector_postmark_key
  }
}

**Expected behavior**

No provider error and provisioned connectors with submitted credentials saved and tested on the Fivetran dashboard.

**Logs & Output**

terraform apply

Postmark

╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to fivetran_connector.postmark, provider "provider[\"registry.terraform.io/fivetran/fivetran\"]" produced an unexpected new value: .config.api_key: inconsistent values for sensitive attribute.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

Gongio:

╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to fivetran_connector.gongio, provider "provider[\"registry.terraform.io/fivetran/fivetran\"]" produced an unexpected new value: .config.username: was cty.StringVal("xxxxxxxxxxx"), but now null.     
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to fivetran_connector.gongio, provider "provider[\"registry.terraform.io/fivetran/fivetran\"]" produced an unexpected new value: .config.password: inconsistent values for sensitive attribute.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

**Plugin version:**

terraform {
  required_providers {
    fivetran = {
      source  = "fivetran/fivetran"
      version = ">= 1.1.20"
    }
  }
}

**Additional context**

**Comment by beevital** [comment]
For `gongio` [correct fields set](https://fivetran.com/docs/rest-api/connectors/config#gong) is:
- access_key
- access_key_secret
- base_url

There was an error in our Open API schema previously.
Other issues caused by wrong sensitive fields handling - PR with the fix raised.
