### ISSUE TITLE
HubSpot Connector setup state reports incomplete during deploy

### ISSUE THREAD

**Issue by agility-adamp** [fivetran/terraform-provider-fivetran#297]
**Describe the bug**
[The docs](https://fivetran.com/docs/rest-api/connectors/config#hubspot) seem to say that we can deploy the HubSpot Connector with no manual intervetion by using a HubSpot access token but it seems to require me to manually click, in the UI, to use FiveTran's pre-built HubSpot app and OAuth.

When I configure my Terraform HubSpot Connector using the `auth.client_access` field, it deploys the same as if I omit the `auth` field altogether.

**To Reproduce**
1. Create a Private App in a properly configured HubSpot Sandbox account
2. Attempt to deploy a FiveTran HubSpot Connector, using the first method in the docs linked above, by specifying the `auth` field with the client secret and account ID from the HubSpot app you've built in the `auth.client_access` field and the `auth.refresh_token` set as the `access token` from the HubSpot app.
3. In the FiveTran UI, navigate to the Destination this Connector is hooked up to
4. Navigate to the HubSpot Connector you've deployed -- Notice that its state is listed as `Incomplete`
5. Navigate to the "Setup" tab, in the Connector
6. Click the "Test Connection" link
At this point, you'll be brought to the Connector's "Edit Setup" page with a couple of notices:
- `Setup test failed with "Failure(origin=(informer=(type=connector, externalName=HubSpot Connector), server=(name=HubSpot, type=SOURCE)), code=auth, message=Unknown authentication or authorization failure.)"`
- `This connector was previously configured using the Fivetran API.`

I'm not sure if the second notice, which is just a warning, is causing the issue.  During the trial, I manually created a Connector to HubSpot.  I am unable to delete that HubSpot FiveTran app in HubSpot and I have super admin permissions there, so that doesn't appear to be an option but I still want to hook this FiveTran Connector up via Terraform, as opposed to manual steps in the FiveTran UI.

This is an example Terraform config that you should be able to reproduce the issue with:
```
resource "fivetran_connector" "hubspot" {
  service              = "hubspot"
  group_id             = fivetran_destination.warehouse.group_id
  run_setup_tests      = "true"

  trust_certificates   = "true"
  trust_fingerprints   = "true"

  auth {
    client_access {
      client_id        = < Insert your HubSpot account ID here >
      client_secret    = < Insert the client secret from the app you built in HubSpot >
    }
    refresh_token      = < Insert the refresh token from the app you built in HubSpot >
  }

  destination_schema {
    name               = "hubspot_${var.env}"
  }
}
```

**Expected behavior**
FiveTran HubSpot Connector is successfully deployed and begins its initial synch with HubSpot, through the specified HubSpot Access Token, and not using the OAuth workflow provided through the public HubSpot FiveTran app.

**Logs & Output**
```
╷
│ Error: Unable to Create Connector Schema Resource.
│
│   with module.fivetran.fivetran_connector_schema_config.hubspot_all,
│   on ../../modules/fivetran/main.tf line 217, in resource "fivetran_connector_schema_config" "hubspot_schema":
│  217: resource "fivetran_connector_schema_config" "hubspot_schema" {
│
│ Error wile schema reload. status code: 400; expected: 200; code:
│ InvalidInput; message: We expected the connector's setup state
│ ('status.setup_state') to be 'connected', but it was 'incomplete'.
│ Please configure the connector and perform the connector setup tests.
```

**Plugin version:**
1.1.21

**Additional context**
The HubSpot app I've built for testing is in the Sandbox account, which is supposed to function just like our Production account.  We've used the Sandbox account in HubSpot to build other integrations, so that should be working.

Thanks!

**Comment by beevital** [comment]
@agility-adamp thank you for the feedback! I've passed your case to the team who maintains HubSpot connector. 
Will update you on results. 

The problem seems to be not related to terraform provider itself, so it's better if you will create a support case on our [support portal](https://support.fivetran.com/)

**Comment by agility-adamp** [comment]
Will do, thanks @beevital 👍

**Comment by beevital** [comment]
Response from maintainers team.
```
It is expected for the customer to pass in both client_id and client_secret when creating a hubspot connector with their private app.

I think this has been already communicated with the customer. This is mentioned in the the connector config on api docs page for hubspot. 

I also tried creating a hubspot connector with private app via terraform, and it is working as expected unless  wrong credentials are passed.
```

@agility-adamp could you please clarify if the case was actually resolved?
I'm planning to close the issue.
