### ISSUE TITLE
Add PrivateLink resource 

### ISSUE THREAD

**Issue by captainjack64** [fivetran/terraform-provider-fivetran#301]
It seems that Fivetran recently added ability to create PrivateLink connections via its API. 

https://fivetran.com/docs/rest-api/private-links-management

It's in private preview but should be available for all soon. Is there a plan to add this to Terraform provider?

**Comment by beevital** [comment]
Hey @captainjack64 ! We are working on it already.

**Comment by captainjack64** [comment]
@beevital is there an ETA on when PrivateLink will be supported?

**Comment by beevital** [comment]
@captainjack64 we prepared a [draft PR](https://github.com/fivetran/terraform-provider-fivetran/pull/328) to support private links, but we can't publish it until it overcomes Private Preview stage on API side.
Once we clarify that the API contract is solid and won't be changed - we will publish appropriate resources.

**Comment by natemellendorf** [comment]
Any update on this request?

I see that the API supports creating connectors with a `private_link_id`, but it's not a valid param to be passed into the TF provider. Was curious if this is looking to be merged in anytime soon.

Else, we need to configure our connectors via API directly. It's possible, but it would be ideal to just use the TF provider and keep everything in sync / in one place (terraform)

**Comment by captainjack64** [comment]
> Any update on this request?

I got fed up waiting, so I used Terraform's REST API provider to do the creation via API through Terraform. A bit hacky but it works fine.

**Comment by davidfm** [comment]
Hi @beevital ,

Can I please check when this would be available? We've recently been granted permissions to create PrivateLinks in a self-service manner. We can create the connector using Terraform, but then we need to "click-ops" the PrivateLink part of it, which isn't ideal. 

<img width="1610" alt="Screenshot 2024-10-24 at 15 42 13" src="https://github.com/user-attachments/assets/49ac7a8e-ab22-4107-b610-9b51b9bfcdc4">

Thanks!

**Comment by captainjack64** [comment]
> Hi @beevital ,
> 
> Can I please check when this would be available? We've recently been granted permissions to create PrivateLinks in a self-service manner. We can create the connector using Terraform, but then we need to "click-ops" the PrivateLink part of it, which isn't ideal.
> 

I gave up waiting and worked around the issue using rest-api Terraform provider and making direct calls to Fivetran endpoint. Works well and no click-ops

**Comment by fivetran-aleksandrboldyrev** [comment]
https://github.com/fivetran/terraform-provider-fivetran/releases/tag/v1.4.0
