### ISSUE TITLE
Missing database for azure_cosmos_for_mongo

### ISSUE THREAD

**Issue by ms32035** [fivetran/terraform-provider-fivetran#302]
**Describe the bug**
Looks like the database field is missing in the mongo confi as we're getting

```
When applying changes to module.hub.fivetran_connector.asset_hub, provider "module.cru_asset_hub.provider[\"registry.terraform.io/fivetran/fivetran\"]" produced an unexpected new value: .config.database: was cty.StringVal("Hub"), but now null.
```

This is a bug in the provider, which should be reported in the provider's own issue tracker.

**To Reproduce**

```
resource "fivetran_connector" "hub" {
  group_id = fivetran_destination.hub.group_id
  service  = "azure_cosmos_for_mongo"

  destination_schema {
    prefix = "hub"
  }

  config {
    hosts           = [var.hub_host]
    user            = var.hub_user
    password        = var.hub_password
    connection_type = "Directly"
    packing_mode    = "UseUnpackedModeOnly"
    database        = "Hub"
  }
}
```

**Expected behavior**

**Logs & Output**

**Plugin version:**
1.22

**Comment by beevital** [comment]
There's no such field in API payload: https://fivetran.com/docs/rest-api/connectors/config#cosmosdbformongodb
There's no option to directly specify database on setup form. PLease refer to our [setup guide Azure CosmosDB for Mongo](https://fivetran.com/docs/connectors/databases/cosmos/cosmos-for-mongo-setup-guide#azurecosmosdbformongodbsetupguide) for details.
