### ISSUE TITLE
OAuth2 Support for Databricks Destination

### ISSUE THREAD

**Issue by ehab-eb** [fivetran/terraform-provider-fivetran#303]
**Is your feature request related to a problem? Please describe.**
Databricks destinations can now use OAuth2 credentials instead of PAT and there is [API support](https://fivetran.com/docs/rest-api/destinations/config#requestforoauth20authentication) for it. 

**Describe the solution you'd like**
Addition of the following fields 

- `config.auth_type`: Can be `PERSONAL_ACCESS_TOKEN` or `OAUTH2`
- `config.oauth2_client_id`: The OAuth Client ID when `config.auth_type` is `OAUTH2`
- `config.oauth2_secret`: The OAuth Client Secret when `config.auth_type` is `OAUTH2`

**Describe the use-cases if possible**
N/A

**Additional context**
When setting up a destination in Fivetran this message is shown `OAuth2.0 is recommended, as personal access token field will be deprecated soon`

**Comment by beevital** [comment]
@ehab-eb thank you for reporting that. We will update OPen API Schema with the next release and the fields will be supported for this flow for sure!

**Comment by beevital** [comment]
Fix included into v1.1.23.

https://registry.terraform.io/providers/fivetran/fivetran/latest/docs/resources/destination#oauth2_client_id
https://registry.terraform.io/providers/fivetran/fivetran/latest/docs/resources/destination#oauth2_secret
