### ISSUE TITLE
Add private_link_id to connector resource config

### ISSUE THREAD

**Issue by Viperal** [fivetran/terraform-provider-fivetran#316]
**Describe the bug**
Based on deployment logs, private_link_id is now required when connection_type is "PrivateLink".  private_link_id is listed in the REST API documentation but is not currently available in the Terraform provider.

Reference: https://fivetran.com/docs/rest-api/connectors#createaconnector

**To Reproduce**
Create a connector with connection_type = "PrivateLink".

```
resource "fivetran_connector" "postgres" {
  service              = "postgres"
  group_id             = fivetran_destination.warehouse.group_id
  run_setup_tests      = "true"

  trust_certificates   = "true"
  trust_fingerprints   = "true"

  destination_schema {
    prefix = "prefix"
  }

  config {
    host             = data.hostname
    port             = data.port
    database         = data.database
    user             = data.username
    password         = data.password
    update_method    = "WAL_PGOUTPUT"
    replication_slot = data.replication_slot_name
    publication_name = data.publication_name

    connection_type      = "PrivateLink"
    always_encrypted      = "false"
  }
}
```

**Expected behavior**
The user is able to configure private_link_id via the terraform provider

**Logs & Output**
```
  fivetran:index:ConnectorSchedule (awards_atd01_development):
    error: Unable to Update Connector Schedule Resource.: status code: 400; expected: 200; code: InvalidInput; message: You must define private_link_id if networking method is set to PrivateLink
```

**Plugin version:**
v1.1.23

**Additional context**
N/A

**Comment by beevital** [comment]
This is a bug in API that will be fixed on API side.

**Comment by beevital** [comment]
@Viperal Private Links feature is in Private Preview state, we will add support for it into Terraform once we will finalize API contract for it.

**Comment by Viperal** [comment]
> This is a bug in API that will be fixed on API side.

Thanks! I've confirmed that the API no longer returns an error when private_link_id is not set.

**Comment by fivetran-aleksandrboldyrev** [comment]
https://github.com/fivetran/terraform-provider-fivetran/releases/tag/v1.4.0
