### ISSUE TITLE
Sharepoint in Magic Folder Mode can't be created

### ISSUE THREAD

**Issue by ryan-pip** [fivetran/terraform-provider-fivetran#335]
**Describe the bug**
When trying to create a sharepoint connector in Magic Folder mode you run into two opposing errors that make this impossible. If you don't specify a table name as per the API documentation you get the following error
`Unable to Create Connector Resource.: `destination_schema.table` field is required to create `share_point` connector;`
If you add a table to the destination schema part of the config you get 
`Unable to Create Connector Resource.: status code: 400; expected: 201; code: InvalidInput; message: Schema name should have a single name without `.` or a table name in the request for Magic Folder mode`

**To Reproduce**
```
resource "fivetran_connector" "sharepoint" {
    group_id = fivetran_group.group.id
    service = "share_point"

    destination_schema {
        name = "test"
    } 

    config {
        share_url= "https://www.example.sharepoint.com"
    }
}
```
or 
```
resource "fivetran_connector" "sharepoint" {
    group_id = fivetran_group.group.id
    service = "share_point"

    destination_schema {
        name = "test"
        table = "placeholder"
    } 

    config {
        share_url= "https://www.example.sharepoint.com"
    }
}
```

**Expected behavior**
The first example should work and recognise for Magic Folder mode that the table is optional

**Plugin version:**
v1.1.24

**Comment by beevital** [comment]
@ryan-pip Thank you for reporting this. We will investigate and prepare a fix.

**Comment by fivetran-jovanmanojlovic** [comment]
New version of terraform-provider ([1.2.9](https://github.com/fivetran/terraform-provider-fivetran/releases/tag/v1.2.9)) is released with the fix, table is no more required
