### ISSUE TITLE
Failed to install provider after new 1.2.5 version release

### ISSUE THREAD

**Issue by neo-eddie-nazarov** [fivetran/terraform-provider-fivetran#338]
**Describe the bug**
--
Getting the following errors after new release 

Error while installing fivetran/fivetran v1.2.5: could not query provider
936 | registry for registry.terraform.io/fivetran/fivetran: failed to retrieve
937 | authentication checksums for provider: 404 Not Found returned from github.com

checking the release in git for 1.2.5 - https://github.com/fivetran/terraform-provider-fivetran/releases, looks off.

**Comment by fivetran-aleksandrboldyrev** [comment]
Could you check again?

**Comment by rdacso** [comment]
@fivetran-aleksandrboldyrev The issue is not resolved. Can you take another look?

**Comment by rdacso** [comment]
We have deployed a solution. There was an issue with the 1.2.5 version of Terraform. We have resolved the issue with the new 1.2.6 version. Please run `terraform init -upgrade` to use the latest provider version.

**Comment by fivetran-aleksandrboldyrev** [comment]
Version 1.2.6 released - it fixed problem with broken release
