### ISSUE TITLE
Google sheet connector in Incomplete State. 

### ISSUE THREAD

**Issue by prakashbalaji** [fivetran/terraform-provider-fivetran#339]
**Describe the bug**
Google sheet connector with ServiceAccount auth type is in incomplete status though the sheet is already shared with the service account. 

**To Reproduce**
```
resource "fivetran_connector" "dummy" {
    group_id = "SomeValidGroupId"
    service = "google_sheets"

    destination_schema {
        name = "some_schema"
        table = "dat_dummy_test"
    }     
    config {
        sheet_id = var.sheet_id
        named_range = "SomeValidNamedRange"
        auth_type = "ServiceAccount"
    }        
}
```

**Expected behavior**
Connector should be created, tested and be in Active condition. 

**Logs & Output**

<img width="856" alt="Screenshot 2024-07-27 at 10 44 27 AM" src="https://github.com/user-attachments/assets/6e72a9f0-0413-4096-9cc9-55386f71c6cb">

**Plugin version:**
1.0.2

**Additional context**
Terraform version 1.8.1
The google sheet was already shared to the service account externally.

**Comment by fivetran-aleksandrboldyrev** [comment]
This is a discrepancy in the documentation, you need to specify the field `run_setup_tests` : true (the documentation says that this is the default value, but this is incorrect). After that, the connector will pass the tests and the setup will be completed

**Comment by prakashbalaji** [comment]
@fivetran-aleksandrboldyrev - Thanks for the pointer and that resolves our issue.

**Comment by prakashbalaji** [comment]
@fivetran-aleksandrboldyrev - Just a follow up on this one, the new connectors are getting created in paused status after putting the `run_setup_tests` flag, is there any flag to run the initial sync as well? I see the api doc had paused boolean, did not see something equivalent in terraform side.
