### ISSUE TITLE
Error: The terraform-provider-fivetran_v1.2.8 plugin crashed!

### ISSUE THREAD

**Issue by juilichormole** [fivetran/terraform-provider-fivetran#352]
**Describe the bug**
When used v1.2.8 for fivetran connector the terraform plan failed with bellow error:
Stack trace from the terraform-provider-fivetran_v1.2.8 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 50 [running]:
github.com/fivetran/terraform-provider-fivetran/fivetran/framework/core/model.(*ConnectorSchemaResourceModel).getSchemasMap(0xc000baaa80, {0xc000a59b40, 0x2, 0x6?})
	github.com/fivetran/terraform-provider-fivetran/fivetran/framework/core/model/connector_schema_config.go:253 +0x15a6
github.com/fivetran/terraform-provider-fivetran/fivetran/framework/core/model.(*ConnectorSchemaResourceModel).ReadFromResponse(0xc000baaa80, {{{0xc000d1b0a0, 0x7}, {0x0, 0x0}}, {{0xc000416270, 0x9}, 0xc000747320}}, 0xc000f2fed8)
	github.com/fivetran/terraform-provider-fivetran/fivetran/framework/core/model/connector_schema_config.go:87 +0x813
github.com/fivetran/terraform-provider-fivetran/fivetran/framework/resources.(*connectorSchema).Read(0x411aa5?, {0xef0738, 0xc000e2a930}, {{{{0xef5d58, 0xc0005a4330}, {0xc74a00, 0xc00095c9f0}}, {0xef8430, 0xc0005743c0}}, 0xc000104520, ...}, ...)
	github.com/fivetran/terraform-provider-fivetran/fivetran/framework/resources/connector_schema_resource.go:352 +0x57b
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0xc00015a4e0, {0xef0738, 0xc000e2a930}, 0xc000e2a990, 0xc0005af6b0)
	github.com/hashicorp/terraform-plugin-framework@v1.8.0/internal/fwserver/server_readresource.go:101 +0x62e
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadResource(0xc00015a4e0, {0xef0738?, 0xc000e2a840?}, 0xc000e2e140)
	github.com/hashicorp/terraform-plugin-framework@v1.8.0/internal/proto6server/server_readresource.go:55 +0x38e
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0xc000378500, {0xef0738?, 0xc000e2a0c0?}, 0xc000d88060)
	github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov6/tf6server/server.go:776 +0x4c3
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0xd666a0, 0xc000378500}, {0xef0738, 0xc000e2a0c0}, 0xc00032e500, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:482 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000b4000, {0xef0738, 0xc00106e810}, {0xef6c00, 0xc0001a8180}, 0xc0006d8ea0, 0xc0003dfce0, 0x14fe1a8, 0x0)
	google.golang.org/grpc@v1.63.2/server.go:1369 +0xdf8
google.golang.org/grpc.(*Server).handleStream(0xc0000b4000, {0xef6c00, 0xc0001a8180}, 0xc0006d8ea0)
	google.golang.org/grpc@v1.63.2/server.go:1780 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 33
	google.golang.org/grpc@v1.63.2/server.go:1030 +0x125

Error: The terraform-provider-fivetran_v1.2.8 plugin crashed!

**Comment by fivetran-aleksandrboldyrev** [comment]
Could you please check on version 1.3.2?
