### ISSUE TITLE
Updating a S3 connector ignore the advanced parameters

### ISSUE THREAD

**Issue by jpetitcolas** [fivetran/terraform-provider-fivetran#362]
**Describe the bug**

When updating a S3 `fivetran_connector`, the following fields (at least) are ignored:

* `config.file_type`
* `config.delimiter`
* `config.escape_char`

Terraform doesn't detect any changes, and the Fivetran connector configuration is not updated.

**To Reproduce**

``` hcl
resource "fivetran_connector" "s3_connector" {
  group_id = var.group_id
  service  = "s3"

  # Assuming a PG destination
  destination_schema {
    name  = "test"
    table = "test_raw"
  }

  config {
    auth_type = "IAM_ROLE"
    role_arn  = var.iam_role

    bucket  = var.bucket_name

    file_type   = "csv"
    delimiter   = ","
    escape_char = "\""
  }
}
```

**Expected behavior**

I would expect Terraform to spot the changes, and the connector configuration to be updated.

**Logs & Output**

The output doesn't detect any changes, and I didn't notice anything particular in logs. Anything you'd like me to extract?

**Plugin version:**

1.3.1

**Additional context**

The workaround is to update the Fivetran connector configuration right from the UI. As Terraform doesn't detect the changes, it won't erase it in the future deployment.

**Comment by fivetran-jovanmanojlovic** [comment]
Hello, I just tested this on the newest version (1.3.2) and I managed to update them. Can you upgrade to a new version and then try again? Thanks.
