### ISSUE TITLE
Google Drive Connector Bug

### ISSUE THREAD

**Issue by ltw94** [fivetran/terraform-provider-fivetran#363]
**Describe the bug**
The connector is complaining about the file_type argument provided.

I'm using version 1.2.9 and the config I have for the google_drive connector is:

```
config = {
    sync_mode = "Magic Folder"
    folder_id = "https://drive.google.com/drive/u/0/folders/{my_folder_id}"
    file_type = "spreadsheet"
  }
```

The output I get is:

```
When applying changes to
│ module.google_drive_connector.fivetran_connector.connector, provider
│ "provider[\"registry.terraform.io/fivetran/fivetran\"]" produced an
│ unexpected new value: .config.file_type: was cty.StringVal("spreadsheet"),
│ but now null.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

**To Reproduce**
Provide an example .tf configuration 

**Expected behavior**

**Logs & Output**
Provide terraform CLI output on `plan` | `apply`. If it is possible, please, refer to [this guide](https://developer.hashicorp.com/terraform/internals/debugging) to enable debug output.

**Plugin version:**
Please specify Fivetran Terraform Provider version you are using.

**Additional context**

**Comment by ltw94** [comment]
HI is there any update on this?

**Comment by fivetran-jovanmanojlovic** [comment]
`file_type` is not expected for `sync_mode = "Magic Folder"`.

So the fix is to remove it from the config.

**Comment by fivetran-aleksandrboldyrev** [comment]
Regarding [API docs](https://fivetran.com/docs/rest-api/interactive-api-reference/api-configuration/connector-configuration#magicfolderrequest_2) file_type field unexpected here. It needs to be removed from the configuration
