### ISSUE TITLE
I want to know the format of this value in destination "region = "GCP_US_EAST4""

### ISSUE THREAD

**Issue by madforchili** [fivetran/terraform-provider-fivetran#371]
**Is your feature request related to a problem? Please describe.**
the destination resource. the region value, what are the available values? or how does this consist of? in the readme file it says GCP_US_EAST4 so i guess, it's "Cloud Service Provider_GCP Region" i can only guess but i want some clear instruction or possible values here

**Describe the solution you'd like**
have this available list in the readme file or at least give format of possible values.

**Comment by fivetran-jovanmanojlovic** [comment]
There is doc with all available regions:
https://fivetran.com/docs/rest-api/powered-by-fivetran/detailed-guide#request

`GCP_US_EAST4,GCP_US_WEST1,GCP_US_CENTRAL1,GCP_EUROPE_WEST3,GCP_AUSTRALIA_SOUTHEAST1,GCP_NORTHAMERICA_NORTHEAST1,GCP_EUROPE_WEST2,GCP_ASIA_SOUTHEAST1,GCP_ASIA_SOUTHEAST2,GCP_ASIA_SOUTH1,GCP_ASIA_NORTHEAST1,AWS_US_EAST_1,AWS_US_EAST_2,AWS_US_WEST_2,AWS_AP_NORTHEAST_1,AWS_AP_SOUTHEAST_1,AWS_AP_SOUTHEAST_2,AWS_EU_CENTRAL_1,AWS_EU_WEST_1,AWS_EU_WEST_2,AWS_AP_SOUTH_1,AWS_CA_CENTRAL_1,AWS_US_GOV_WEST_1,AZURE_EASTUS2,AZURE_AUSTRALIAEAST,AZURE_UKSOUTH,AZURE_WESTEUROPE,AZURE_CENTRALUS,AZURE_CANADACENTRAL,AZURE_UAENORTH,AZURE_SOUTHEASTASIA,AZURE_EASTUS,AZURE_JAPANEAST,AZURE_CENTRALINDIA.
`
