### ISSUE TITLE
How can I manage "Historical Sync Time Frame" for Google Analytics 4

### ISSUE THREAD

**Issue by madforchili** [fivetran/terraform-provider-fivetran#375]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/user-attachments/assets/a0fe8140-4577-44b8-a22d-66d29f172cb0)

for Google Analytics 4 connector. how can I update "Historical Sync Time Frame" via Terraform?

i tried to use "historic_sync_time_frame" with value "3 months" or "3M" 

╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to fivetran_connector.google_analytics_4, provider
│ "provider[\"registry.terraform.io/fivetran/fivetran\"]" produced an
│ unexpected new value: .config.historic_sync_time_frame: was
│ cty.StringVal("3 months"), but now null.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵

if this is the right place to manage, what is available values? I couldn't find any information around it

**Comment by fivetran-aleksandrboldyrev** [comment]
For this connector, this field is called `timeframe_months`
We are working on improving the documentation - we plan to make it individual for each service instead of the general one as it is now
