### ISSUE TITLE
Support for Team Management

### ISSUE THREAD

**Issue by amelentyev** [fivetran/terraform-provider-fivetran#72]
Hello!

I'm curious to know if supporting the [Team Management API](https://fivetran.com/docs/rest-api/teams)  is something you guys have on your roadmap and if so if there's any timeline for that?

Best
Andrey

**Comment by beevital** [comment]
Hey Andrey! 

Yes, we have plans to support Team Management via Terraform provider but unfortunately I can't give you exact timeline.

We will take your request into account when prioritizing tasks. Thank you for highlighting this!

**Comment by beevital** [comment]
I'll keep this issue for tracking

**Comment by Lindblomsebastian** [comment]
Hi @beevital, in your contributing guidelines in both this repo and in [go-fivetran](https://github.com/fivetran/go-fivetran) you state that you're not ready to accept external contributions. Could you consider making an exception? Me and @ylva-lundegard are interested in extending the terraform provider to add support for this issue. 
Of course pending reviewing from you guys.

**Comment by beevital** [comment]
Hey @Lindblomsebastian, now we are not ready to accept external contributions because of lack of testing infrastructure. 

We are working on it currently and I hope one day we will provide guide or how-to for writing tests with mocked API (as we are doing it now) within the updated contribution guidelines =)

**Comment by fivetran-aleksandrboldyrev** [comment]
Released in 1.1.1 (https://github.com/fivetran/terraform-provider-fivetran/releases/tag/v1.1.1)
