### ISSUE TITLE
Support for Webhook Management

### ISSUE THREAD

**Issue by dominicroessner** [fivetran/terraform-provider-fivetran#74]
Are there any plans to support [Webhook Management API](https://fivetran.com/docs/rest-api/webhooks#webhookmanagement_1) with the Terraform provider? If so, is there a timeline when this could be expected?

**Comment by fivetran-jimmyhooker** [comment]
We eventually want to get parity between the API and all our providers/dependencies, but we're not quite there yet. How are you looking to utilize our webhooks via Terraform?

**Comment by chrisweis** [comment]
> How are you looking to utilize our webhooks via Terraform?

I'd like to deploy a Webhook connector via Terraform without needing to use the FiveTran GUI.  Example: FiveTran doesn't support Momentive GetFeedback as a source and we needed to instead use the Webhook feature in both platforms to flow survey data into Snowflake.

**Comment by fivetran-aleksandrboldyrev** [comment]
Released in [v1.1.0](https://github.com/fivetran/terraform-provider-fivetran/releases/tag/v1.1.0)
