### ISSUE TITLE
API request limit

### ISSUE THREAD

**Issue by quasi-coherent** [fivetran/terraform-provider-fivetran#80]
The S3 connector [is not intelligent enough](https://support.fivetran.com/hc/en-us/community/posts/7778751318295-Connector-Improvement-Multiple-table-load-option-for-a-single-S3-Connector) to figure out that perhaps many tables lie behind a given prefix.  This requires making a connector for every single file that lies at the bottom of a given prefix.

This is problematic for many reasons.  The problem this post is about is API request limits reached by using a `terraform apply` while trying to deploy programmatically created `fivetran_connector`s.  

I have thirty or so individual files underneath different prefixes, duplicated across different buckets.  All of these buckets, and the prefixes, and the files, follow the same pattern because they come from the same application deployed in many AWS regions and accounts.  I would like to write programmatic Terraform code to deploy connectors for each of these instances at once.  This amounts to something like 250 Terraform resources, which is absurd.  

So, I suppose this should obvious:

```
 status code: 429; expected: 201; code: TooManyRequests; message: No more than 20 connectors can be created in one-minute  time period
```

Do you expect that people who use this provider try to import less that twenty files at a time?  If not, can you build something into this to perform some backoff on requests so that I don't have to do a `terraform apply` fifteen times before finally everything is created?  

Or, much better (so much better): can the core Fivetran team make S3 connectors usable for a team not trying to copy three files?  I can envision how it would not be hard to do the same inference for many S3 objects given what you already can do for one single object.  Just recurse through all the objects in the prefix and apply the same inference...

Having said that, I'm probably going to go with anything else after experiencing Fivetran for the first time.

**Comment by amelentyev** [comment]
We're running into the same issue with the GCS connector. It'd be nice to better handle TooManyRequests in the provider. And it'd be nice to make the GCS connector smarter so that we don't have to create an instance per table.

**Comment by beevital** [comment]
This will be a good improvement. 
Created internal ticket for rate limiting issue handling.

**Comment by fivetran-jimmyhooker** [comment]
I think we have a few things we can consider:
- Better rate limit handling in Terraform
- Increase our rate limits, specifically for connector creation
- Think about how we could improve S3/GCS connectors for these use cases. For these, could you [create a feature request](https://support.fivetran.com/hc/en-us/community/topics/360001909373-Feature-Requests) @amelentyev @quasi-coherent? Product uses these directly to inform development.

**Comment by beevital** [comment]
We had reviewed our API limits on API side, now the problem should be resolved.
