### ISSUE TITLE
feature request: external id data source 

### ISSUE THREAD

**Issue by Tsanton** [fivetran/terraform-provider-fivetran#90]
Hi,

In reference to [Amazon S3 Setup Guide (get your external id)](https://fivetran.com/docs/files/amazon-s3/setup-guide#getyourexternalid), is it possible for you to supply `Data Source: fivetran_external_id`?

**Comment by beevital** [comment]
@Tsanton Let me know if it works for you, please.

**Comment by Tsanton** [comment]
Cheers -> Will have a look at it tomorrow evening :)
Thanks!

**Comment by beevital** [comment]
I suppose we can close this issue.
