### ISSUE TITLE
feature request: dbt projects and transformations

### ISSUE THREAD

**Issue by ldnicolasmay** [fivetran/terraform-provider-fivetran#95]
Suggestion to create/manage dbt projects and transformations in Terraform. 

Public interfaces for creation:
* https://developers.fivetran.com/openapi/reference/v1/operation/create_dbt_project/
* https://developers.fivetran.com/openapi/reference/v1/operation/create_dbt_transformation/

Thank you!

**Comment by beevital** [comment]
Dbt Transformation management is available [in latest v1.0.1](https://registry.terraform.io/providers/fivetran/fivetran/1.0.1)

Dbt project management coming soon:
https://github.com/fivetran/terraform-provider-fivetran/pull/194

**Comment by ldnicolasmay** [comment]
This is great. Thanks @beevital !

**Comment by beevital** [comment]
Supported in v1.1.0
